const estacoes = [
  // ==================== NACIONAL ====================
  { id: 0, nome: "Rádio Moçambique", desc: "Empresa pública de radiodifusão", regiao: "Nacional", categoria: "Notícias", urlStream: "https://stream.zeno.fm/tskpv4vscv8uv.mp3" },
  { id: 1, nome: "RM Desporto", desc: "Canal de desporto - A Rádio dos Campeões", regiao: "Nacional", categoria: "Desporto", urlStream: "https://node.stream-africa.com:8443/RMDesporto" },
  { id: 2, nome: "99 FM", desc: "Connecting - Rádio generalista", regiao: "Sul", categoria: "Música", urlStream: "https://streaming2.99fm.co.mz/stream" },
  { id: 3, nome: "Rádio Miramar", desc: "Em boa companhia - Rádio privada", regiao: "Sul", categoria: "Generalista", urlStream: "https://nl.digitalrm.pt:8150/stream" },
  { id: 4, nome: "Super FM", desc: "Música elevada ao infinito", regiao: "Sul", categoria: "Pop", urlStream: "http://54.39.28.158:9720/stream" },
  { id: 5, nome: "Rádio Moçambique Gospel", desc: "Fé, esperança e louvor", regiao: "Nacional", categoria: "Gospel", urlStream: "https://stream.zeno.fm/12q9fqsxbg8uv" },
  { id: 6, nome: "LM Radio", desc: "Happy Listening - Estação histórica", regiao: "Nacional", categoria: "Easy-Listening", urlStream: "https://ukwesta.streaming.broadcast.radio/lmradio" },
  { id: 7, nome: "Rádio Moçambique 97.9", desc: "Canal RM", regiao: "Nacional", categoria: "Notícias", urlStream: "https://stream.streamgenial.stream/0tcgy4vscv8uv" },

  // ==================== SUL ====================
  { id: 8, nome: "RM - EP Maputo", desc: "Hoje e sempre projetando Moçambique", regiao: "Sul", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/MaputoFM" },
  { id: 9, nome: "Rádio Cidade", desc: "Mais Rádio Do Rovuma a Maputo", regiao: "Sul", categoria: "Música", urlStream: "https://node.stream-africa.com:8443/RadioCidadeMaputo" },
  { id: 10, nome: "Maputo Corridor Radio", desc: "Your News and Music Station - English Service", regiao: "Sul", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/MaputoCorridor" },
  { id: 11, nome: "Rádio S FM", desc: "SFM - Ouve o som que te toca", regiao: "Sul", categoria: "Pop", urlStream: "http://pesquisa.sapo.mz/?q=sfm&host=sfm.sapo.mz", tipo: "web" },
  { id: 12, nome: "Rádio Planeta Rap Lu So", desc: "Rap e Hip-Hop", regiao: "Sul", categoria: "Rap/Hip-Hop", urlStream: "https://portalplanetarapluso.blogspot.com", tipo: "web" },
  { id: 13, nome: "kampua FM", desc: "Variedades", regiao: "Sul", categoria: "Variedades", urlStream: "https://zeno.fm/player/kampua-fm-kjha", tipo: "web" },
  { id: 14, nome: "Radio EGEA Web 24hrs", desc: "Rádio gospel - Heaven Full", regiao: "Sul", categoria: "Gospel", urlStream: "https://stream.zeno.fm/gbktm9u0czzuv" },
  { id: 15, nome: "RM - EP Gaza", desc: "Do Rovuma a Maputo", regiao: "Sul", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/Gaza" },
  { id: 16, nome: "ICS - Rádio Comunitária de Xai-Xai 107.1 FM", desc: "Comunicar para o desenvolvimento das comunidades", regiao: "Sul", categoria: "Comunitária", urlStream: "https://stream.zeno.fm/x7ht0dkxpgtvv" },
  { id: 17, nome: "Limpopo FM 107.7", desc: "Transmitindo de Xai-Xai para o Mundo e África", regiao: "Sul", categoria: "Generalista", urlStream: "https://stream.zeno.fm/mzzal6abxkeuv" },
  { id: 18, nome: "RM - EP Inhambane", desc: "Hoje e sempre projetando Moçambique", regiao: "Sul", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/InhambaneFM" },
  { id: 19, nome: "Rádio Índico", desc: "Cada vez mais ouvida", regiao: "Sul", categoria: "World", urlStream: "http://uk16freenew.listen2myradio.com:8125/" },
  { id: 20, nome: "Rádio Maria Moçambique", desc: "Uma voz cristã em sua casa", regiao: "Sul", categoria: "Religiosa", urlStream: "https://dreamsiteradiocp2.com/proxy/rmmozambique2?mp=/stream" },
  { id: 21, nome: "Rádio Capital 90.7 FM", desc: "Emissora cristã", regiao: "Sul", categoria: "Religiosa", urlStream: "https://stream.zeno.fm/hr0guxs2tlguv" },
  { id: 22, nome: "KFM 88.3 MHZ Moçambique", desc: "Rádio religiosa", regiao: "Sul", categoria: "Religiosa", urlStream: "https://stream.zeno.fm/4fcgv64r1uhvv" },
  { id: 23, nome: "Rádio Alfa Ómega", desc: "Sinônimo de Esperança", regiao: "Sul", categoria: "Religiosa", urlStream: "https://www.copromel.org/radio", tipo: "web" },
  { id: 24, nome: "Hero Radio", desc: "Rádio gospel", regiao: "Sul", categoria: "Gospel", urlStream: "https://a2.asurahosting.com:6790/mozambique.mp3" },
  { id: 25, nome: "Favor Radio", desc: "Rádio gospel oficial", regiao: "Sul", categoria: "Gospel", urlStream: "https://www.facebook.com/favorradioofficial", tipo: "web" },

  // ==================== CENTRO ====================
  { id: 26, nome: "Cidade FM", desc: "Mais Rádio - Beira", regiao: "Centro", categoria: "Música", urlStream: "https://node.stream-africa.com:8443/RadioCidadeBeira" },
  { id: 27, nome: "Rádio Sofala FM", desc: "Hoje e sempre projetando Moçambique", regiao: "Centro", categoria: "Comunitária", urlStream: "https://node.stream-africa.com:8443/Sofala" },
  { id: 28, nome: "RM - EP Sofala", desc: "Emissão provincial", regiao: "Centro", categoria: "Notícias", urlStream: "http://node.stream-africa.com:8000/Sofala" },
  { id: 29, nome: "Rádio Pax", desc: "Emissora Católica da Beira - Promovendo a Paz", regiao: "Centro", categoria: "Religiosa", urlStream: "https://www.radiopax.net", tipo: "web" },
  { id: 30, nome: "Iembe Rádio Cristã", desc: "Igreja Evangélica na Beira", regiao: "Centro", categoria: "Gospel", urlStream: "https://stream.zeno.fm/8jaq9bzwi6quv" },
  { id: 31, nome: "RM - EP Manica", desc: "Hoje e sempre projetando Moçambique", regiao: "Centro", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/ManicaFM" },
  { id: 32, nome: "RM - EP Tete", desc: "Hoje e Sempre", regiao: "Centro", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/TeteFM" },
  { id: 33, nome: "RM - EP Zambézia", desc: "Hoje e sempre projetando Moçambique", regiao: "Centro", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/ZambeziaFM" },
  { id: 34, nome: "RTZ (Rádio Televisão da Zambézia)", desc: "Audiência Total e Sintonia Perfeita", regiao: "Centro", categoria: "Comunitária", urlStream: "https://fpsnew2.listen2myradio.com:2199/listen.php?ip=212.84.160.3&port=5427&type=ice&mount=stream" },
  { id: 35, nome: "Chuabo FM", desc: "Liberdade Independência", regiao: "Centro", categoria: "Comunitária", urlStream: "https://chuabofm.com", tipo: "web" },
  { id: 36, nome: "Rádio Mega FM", desc: "A rádio das grandes emoções", regiao: "Centro", categoria: "Música", urlStream: "https://stream.zeno.fm/71nw1dw9ioyuv" },

  // ==================== NORTE ====================
  { id: 37, nome: "RM - EP Nampula", desc: "Do Rovuma a Maputo", regiao: "Norte", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/Nampula" },
  { id: 38, nome: "Rádio Encontro", desc: "Emissora Católica de Nampula", regiao: "Norte", categoria: "Religiosa", urlStream: "https://www.radioencontro.co.mz", tipo: "web" },
  { id: 39, nome: "Rádio Vida Nampula 88.8 FM", desc: "Emissora Evangélica de Nampula", regiao: "Norte", categoria: "Gospel", urlStream: "https://stream.zeno.fm/xx59uigxs32vv" },
  { id: 40, nome: "Rádio Watana", desc: "A Rádio Católica da Diocese da Nacala", regiao: "Norte", categoria: "Religiosa", urlStream: "https://radiowatana.org", tipo: "web" },
  { id: 41, nome: "Rádio Comunitária de Monapo", desc: "Comunicando e informando a comunidade", regiao: "Norte", categoria: "Comunitária", urlStream: "https://radiomonapo.org", tipo: "web" },
  { id: 42, nome: "Tribo FM", desc: "Rádio online de Nampula", regiao: "Norte", categoria: "Música", urlStream: "http://sites.google.com/view/webradio-tribofm", tipo: "web" },
  { id: 43, nome: "Radio Vida", desc: "Rádio Evangélica de Nampula", regiao: "Norte", categoria: "Gospel", urlStream: "https://stream.zeno.fm/raqujgb9xrbvv" },
  { id: 44, nome: "RM - EP Niassa", desc: "Hoje e sempre projetando Moçambique", regiao: "Norte", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/NiassaFM" },
  { id: 45, nome: "Rádio FOT Lichinga 95.9 FM", desc: "Rádio FOT FM, o nosso futuro já chegou", regiao: "Norte", categoria: "Religiosa", urlStream: "https://stream.zeno.fm/vk1yf5a8z98uv" },
  { id: 46, nome: "RM - EP Cabo Delgado", desc: "Hoje e sempre projetando Moçambique", regiao: "Norte", categoria: "Notícias", urlStream: "https://node.stream-africa.com:8443/CaboDelgadoFM" },
  { id: 47, nome: "Rádio Sem Fronteiras", desc: "Emissora católica da Diocese de Pemba", regiao: "Norte", categoria: "Religiosa", urlStream: "https://ssl.stmxp.net:8030/" },
  { id: 48, nome: "Rádio Wimbe", desc: "Rádio religiosa - Pemba", regiao: "Norte", categoria: "Religiosa", urlStream: "https://xstreamer.galcom.org:8443/RadioWimbeOgg" },
  { id: 49, nome: "Zumbo FM", desc: "O Ouvinte em Primeiro Lugar", regiao: "Norte", categoria: "Música", urlStream: "https://zumbofm.com/stream.html", tipo: "web" },
  { id: 50, nome: "site moz FM", desc: "Música para todos em grande estilo", regiao: "Norte", categoria: "Música", urlStream: "https://stream.zeno.fm/5qywky45rxhvv" },
  { id: 51, nome: "Notícias do Norte Rádio", desc: "Informação do norte", regiao: "Norte", categoria: "Notícias", urlStream: "https://stream.zeno.fm/f6ss7utfzrhvv" },

  // ==================== MOÇAMBIQUE (Diversas) ====================
  { id: 52, nome: "Rádio Notas De Prata", desc: "Além da imaginação", regiao: "Moçambique", categoria: "Variedades", urlStream: "https://stream.zeno.fm/dzppe218g18uv" },
  { id: 53, nome: "Tars FM", desc: "Rede Tars", regiao: "Moçambique", categoria: "Rock", urlStream: "https://stm.roxcast.com.br:7030/" },
  { id: 54, nome: "AFRO Rádio", desc: "Música e muito mais", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/3p12umu90s8uv" },
  { id: 55, nome: "B5 Radio MZ", desc: "No Borders In Music", regiao: "Moçambique", categoria: "R&B", urlStream: "https://stream.zeno.fm/wu2zvliloxtuv" },
  { id: 56, nome: "Belarte FM", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/uwpccsaf9yzuv" },
  { id: 57, nome: "DK Record", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/sg7vsmvwzp8uv" },
  { id: 58, nome: "Grandes Clássicos da Música Moçambicana", desc: "Clássicos nacionais", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/bm29ouxe0hrtv" },
  { id: 59, nome: "Infor Radio", desc: "News, Music and Entertainment", regiao: "Moçambique", categoria: "Notícias", urlStream: "https://stream.zeno.fm/t54yw7vc0rhvv" },
  { id: 60, nome: "MAC Rádio Fusão FM 91.6", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "http://zeno.fm/radio/mac-radio-fusao-fm-91-6", tipo: "web" },
  { id: 61, nome: "Mmradio Entrevistas Online", desc: "Entrevistas e música", regiao: "Moçambique", categoria: "Entrevistas", urlStream: "https://stream.zeno.fm/tk497a3sgxhvv" },
  { id: 62, nome: "Rádio Banda RJ", desc: "Une Moçambique e África lusófona", regiao: "Moçambique", categoria: "Generalista", urlStream: "https://stream.zeno.fm/wgo68netouhvv" },
  { id: 63, nome: "Rádio Cabeça do Velho", desc: "Música moçambicana e do mundo", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/3me12q256nhvv" },
  { id: 64, nome: "Rádio Capoeira", desc: "Esportes", regiao: "Moçambique", categoria: "Desporto", urlStream: "https://stream.zeno.fm/tkppachyeolvv" },
  { id: 65, nome: "Rádio CF 91.2", desc: "A sua rádio mais ouvida", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/68gh568f5nhvv" },
  { id: 66, nome: "Rádio Chissano", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/8oxxfsxzpftvv" },
  { id: 67, nome: "Rádio Clube de Jovens", desc: "Conectando Jovens", regiao: "Moçambique", categoria: "Juvenil", urlStream: "https://stream.zeno.fm/t67546r8038uv" },
  { id: 68, nome: "Rádio Despertar MZ", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/167qkkygvnhvv" },
  { id: 69, nome: "Rádio FM Web-Namacurra", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/jh2htf8itpotv" },
  { id: 70, nome: "Rádio Imacs Chókwe", desc: "Sempre na Linha da Frente", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/qgfxqcnsyzxtv" },
  { id: 71, nome: "Rádio Martins", desc: "Todas Novidades", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/bbbpxwnpj70tv" },
  { id: 72, nome: "Rádio Terra", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/vinnpmoaqopvv" },
  { id: 73, nome: "radiobranquinhocosta", desc: "Web rádio", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream.zeno.fm/a3gbe3ewqjftv" },
  { id: 74, nome: "Superior FM", desc: "Informação, Educação e Entretenimento", regiao: "Moçambique", categoria: "Educacional", urlStream: "https://stream.zeno.fm/9v34uaukdq8uv" },
  { id: 75, nome: "Viva Rádio", desc: "Rádio educacional", regiao: "Moçambique", categoria: "Educacional", urlStream: "https://stream.zeno.fm/hv7y8teaaf9uv" },
  { id: 76, nome: "Conexão 360", desc: "Promoção de acontecimentos do país", regiao: "Moçambique", categoria: "Notícias", urlStream: "https://stream.zeno.fm/d1nhbf70tchvv" },
  { id: 77, nome: "Rádio FIM", desc: "Web rádio", regiao: "Moçambique", categoria: "Notícias", urlStream: "https://stream.zeno.fm/stxdzvs44c9uv" },
  { id: 78, nome: "Rádio Académica", desc: "Rádio académica do ISCTAC", regiao: "Moçambique", categoria: "Educacional", urlStream: "https://stream.zeno.fm/f32qntg3srhvv" },
  { id: 79, nome: "Rádio RTMC", desc: "Rádio educativa e cultural", regiao: "Moçambique", categoria: "Educacional", urlStream: "https://acmc.ice.infomaniak.ch/acmc-32.mp3" },
  { id: 80, nome: "Rádio 5", desc: "Stream Africa", regiao: "Moçambique", categoria: "Música", urlStream: "https://stream-africa.com", tipo: "web" },
  { id: 81, nome: "LM Radio Moçambique", desc: "LM Radio local", regiao: "Moçambique", categoria: "Easy-Listening", urlStream: "http://lmradio.co.mz", tipo: "web" }
];